### ISSUE TITLE
I GOT A BUG ON Q16 AND Q17

### ISSUE THREAD

**Issue by raghav517** [Spaceyy64/RakshaKavach#1]
Q17 AND Q16 HAS A PROBLEM THAT AFTER SELECTING OPTIONS OF Q17  INSTEAD OF REGISTERING ON HIS OWN FRIKIN WHITE BOX  IT GETS REGISTERED ON THE WHITE BOX OF Q16

**Comment by Spaceyy64** [comment]
Thanks for pointing it out! Will work on this soon.

**Comment by raghav517** [comment]
IN Q5 IN THE OPTION DROPDOWN MENU ''MOSTLY MANAGABLE'' AND "AND NOTMANAGABLE" SEEM TO BE SWAPPED :}

**Comment by Spaceyy64** [comment]
Thanks for your contribution, the bug has been fixed.
